-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Front.

module Language.Sprite.Syntax.Front.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

import qualified Data.Data    as C (Data, Typeable)
import qualified GHC.Generics as C (Generic)

data Program = Program [Qualifier] Term
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Qualifier = Qualifier VarIdent [QualifierArg] Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data QualifierArg = QualifierArg VarIdent BaseType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Term
    = ConstInt Integer
    | Bool ConstBool
    | Var VarIdent
    | If FuncAppArg Term Term
    | Let Decl ScopedTerm
    | Fun VarIdent ScopedTerm
    | App Term FuncAppArg
    | Op FuncAppArg IntOp FuncAppArg
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data ConstBool = ConstTrue | ConstFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Annotation = Annotation VarIdent RType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Decl
    = RecDecl Annotation VarIdent Term
    | AnnotatedDecl Annotation VarIdent Term
    | UnAnnotatedDecl VarIdent Term
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data IntOp
    = IntPlus
    | IntMinus
    | IntMultiply
    | IntEq
    | IntLessThan
    | IntLessOrEqThan
    | IntGreaterThan
    | IntGreaterOrEqThan
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data RType
    = TypeRefined BaseType VarIdent Pred
    | TypeRefinedUnknown BaseType
    | TypeFun FuncArg ScopedRType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data ScopedRType = ScopedRType RType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data FuncArg = NamedFuncArg VarIdent RType
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Pred
    = PVar VarIdent
    | PBool ConstBool
    | PInt Integer
    | PEq Pred Pred
    | PLessThan Pred Pred
    | PLessOrEqThan Pred Pred
    | PGreaterThan Pred Pred
    | PGreaterOrEqThan Pred Pred
    | PPlus Pred Pred
    | PMinus Pred Pred
    | PMultiply Pred Pred
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data Pattern = PatternVar VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data ScopedTerm = ScopedTerm Term
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data BaseType = BaseTypeInt | BaseTypeBool
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

data FuncAppArg
    = FuncAppArgBool ConstBool
    | FuncAppArgInt Integer
    | FuncAppArgVar VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Data, C.Typeable, C.Generic, Data.String.IsString)

