-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Language.Sprite.Syntax.Front.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Language.Sprite.Syntax.Front.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Language.Sprite.Syntax.Front.Abs.VarIdent -> Result
transVarIdent x = case x of
  Language.Sprite.Syntax.Front.Abs.VarIdent string -> failure x

transConIdent :: Language.Sprite.Syntax.Front.Abs.ConIdent -> Result
transConIdent x = case x of
  Language.Sprite.Syntax.Front.Abs.ConIdent string -> failure x

transProgram :: Language.Sprite.Syntax.Front.Abs.Program -> Result
transProgram x = case x of
  Language.Sprite.Syntax.Front.Abs.Program qualifiers measures datatypes term -> failure x

transQualifier :: Language.Sprite.Syntax.Front.Abs.Qualifier -> Result
transQualifier x = case x of
  Language.Sprite.Syntax.Front.Abs.Qualifier varident qualifierargs pred -> failure x

transQualifierArg :: Language.Sprite.Syntax.Front.Abs.QualifierArg -> Result
transQualifierArg x = case x of
  Language.Sprite.Syntax.Front.Abs.QualifierArg varident basetype -> failure x

transMeasure :: Language.Sprite.Syntax.Front.Abs.Measure -> Result
transMeasure x = case x of
  Language.Sprite.Syntax.Front.Abs.Measure varident rtype -> failure x

transTerm :: Language.Sprite.Syntax.Front.Abs.Term -> Result
transTerm x = case x of
  Language.Sprite.Syntax.Front.Abs.ConstInt integer -> failure x
  Language.Sprite.Syntax.Front.Abs.Bool constbool -> failure x
  Language.Sprite.Syntax.Front.Abs.Var varident -> failure x
  Language.Sprite.Syntax.Front.Abs.ConApp conident conappargs -> failure x
  Language.Sprite.Syntax.Front.Abs.FunApp varident funcappargs -> failure x
  Language.Sprite.Syntax.Front.Abs.If funcapparg term1 term2 -> failure x
  Language.Sprite.Syntax.Front.Abs.Let decl term -> failure x
  Language.Sprite.Syntax.Front.Abs.Fun funargnames term -> failure x
  Language.Sprite.Syntax.Front.Abs.Op funcapparg1 intop funcapparg2 -> failure x
  Language.Sprite.Syntax.Front.Abs.Switch varident switchcases -> failure x

transConstBool :: Language.Sprite.Syntax.Front.Abs.ConstBool -> Result
transConstBool x = case x of
  Language.Sprite.Syntax.Front.Abs.ConstTrue -> failure x
  Language.Sprite.Syntax.Front.Abs.ConstFalse -> failure x

transConAppArgs :: Language.Sprite.Syntax.Front.Abs.ConAppArgs -> Result
transConAppArgs x = case x of
  Language.Sprite.Syntax.Front.Abs.EmptyConAppArgs -> failure x
  Language.Sprite.Syntax.Front.Abs.NonEmptyConAppArgs funcappargs -> failure x

transAnnotation :: Language.Sprite.Syntax.Front.Abs.Annotation -> Result
transAnnotation x = case x of
  Language.Sprite.Syntax.Front.Abs.Annotation varident rtype -> failure x

transDecl :: Language.Sprite.Syntax.Front.Abs.Decl -> Result
transDecl x = case x of
  Language.Sprite.Syntax.Front.Abs.RecDecl annotation varident term -> failure x
  Language.Sprite.Syntax.Front.Abs.AnnotatedDecl annotation varident term -> failure x
  Language.Sprite.Syntax.Front.Abs.UnAnnotatedDecl varident term -> failure x

transSwitchCase :: Language.Sprite.Syntax.Front.Abs.SwitchCase -> Result
transSwitchCase x = case x of
  Language.Sprite.Syntax.Front.Abs.SwitchCase varident switchcasedataconargs term -> failure x

transSwitchCaseDataConArgs :: Language.Sprite.Syntax.Front.Abs.SwitchCaseDataConArgs -> Result
transSwitchCaseDataConArgs x = case x of
  Language.Sprite.Syntax.Front.Abs.SwitchCaseNonEmptyDataConArgs funargnames -> failure x
  Language.Sprite.Syntax.Front.Abs.SwitchCaseEmptyDataConArgs -> failure x

transIntOp :: Language.Sprite.Syntax.Front.Abs.IntOp -> Result
transIntOp x = case x of
  Language.Sprite.Syntax.Front.Abs.IntPlus -> failure x
  Language.Sprite.Syntax.Front.Abs.IntMinus -> failure x
  Language.Sprite.Syntax.Front.Abs.IntMultiply -> failure x
  Language.Sprite.Syntax.Front.Abs.IntEq -> failure x
  Language.Sprite.Syntax.Front.Abs.IntLessThan -> failure x
  Language.Sprite.Syntax.Front.Abs.IntLessOrEqThan -> failure x
  Language.Sprite.Syntax.Front.Abs.IntGreaterThan -> failure x
  Language.Sprite.Syntax.Front.Abs.IntGreaterOrEqThan -> failure x

transRefinement :: Language.Sprite.Syntax.Front.Abs.Refinement -> Result
transRefinement x = case x of
  Language.Sprite.Syntax.Front.Abs.KnownRefinement varident pred -> failure x
  Language.Sprite.Syntax.Front.Abs.UnknownRefinement -> failure x
  Language.Sprite.Syntax.Front.Abs.SimpleRefinement -> failure x

transRType :: Language.Sprite.Syntax.Front.Abs.RType -> Result
transRType x = case x of
  Language.Sprite.Syntax.Front.Abs.TypeFun funcarg rtype -> failure x
  Language.Sprite.Syntax.Front.Abs.TypeRefined basetype refinement -> failure x
  Language.Sprite.Syntax.Front.Abs.TypeData varident typedataargs refinement -> failure x

transTypeDataArg :: Language.Sprite.Syntax.Front.Abs.TypeDataArg -> Result
transTypeDataArg x = case x of
  Language.Sprite.Syntax.Front.Abs.TypeDataArg rtype -> failure x

transTypeDataArgs :: Language.Sprite.Syntax.Front.Abs.TypeDataArgs -> Result
transTypeDataArgs x = case x of
  Language.Sprite.Syntax.Front.Abs.NonEmptyTypeDataArgs typedataargs -> failure x
  Language.Sprite.Syntax.Front.Abs.EmptyTypeDataArgs -> failure x

transDataType :: Language.Sprite.Syntax.Front.Abs.DataType -> Result
transDataType x = case x of
  Language.Sprite.Syntax.Front.Abs.DataType varident datatypeargs datatypeconstructors -> failure x

transDataTypeConstructor :: Language.Sprite.Syntax.Front.Abs.DataTypeConstructor -> Result
transDataTypeConstructor x = case x of
  Language.Sprite.Syntax.Front.Abs.DataTypeConstructor conident datatypeconstructorargs datatypeconstructorpredicate -> failure x

transDataTypeConstructorArgs :: Language.Sprite.Syntax.Front.Abs.DataTypeConstructorArgs -> Result
transDataTypeConstructorArgs x = case x of
  Language.Sprite.Syntax.Front.Abs.NonEmptyDataTypeConstructorArgs funcargs -> failure x
  Language.Sprite.Syntax.Front.Abs.EmptyDataTypeConstructorArgs -> failure x

transDataTypeConstructorPredicate :: Language.Sprite.Syntax.Front.Abs.DataTypeConstructorPredicate -> Result
transDataTypeConstructorPredicate x = case x of
  Language.Sprite.Syntax.Front.Abs.NonEmptyDataTypeConstructorPredicate varident pred -> failure x
  Language.Sprite.Syntax.Front.Abs.EmptyDataTypeConstructorPredicate -> failure x

transDataTypeArgs :: Language.Sprite.Syntax.Front.Abs.DataTypeArgs -> Result
transDataTypeArgs x = case x of
  Language.Sprite.Syntax.Front.Abs.NonEmptyDataTypeArgs typevarids -> failure x
  Language.Sprite.Syntax.Front.Abs.EmptyDataTypeArgs -> failure x

transFuncArg :: Language.Sprite.Syntax.Front.Abs.FuncArg -> Result
transFuncArg x = case x of
  Language.Sprite.Syntax.Front.Abs.NamedFuncArg varident rtype -> failure x
  Language.Sprite.Syntax.Front.Abs.UnNamedFuncArg rtype -> failure x

transPred :: Language.Sprite.Syntax.Front.Abs.Pred -> Result
transPred x = case x of
  Language.Sprite.Syntax.Front.Abs.PVar varident -> failure x
  Language.Sprite.Syntax.Front.Abs.PBool constbool -> failure x
  Language.Sprite.Syntax.Front.Abs.PInt integer -> failure x
  Language.Sprite.Syntax.Front.Abs.PMeasure varident funargnames -> failure x
  Language.Sprite.Syntax.Front.Abs.POr pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PAnd pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PEq pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PLessThan pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PLessOrEqThan pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PGreaterThan pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PGreaterOrEqThan pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PPlus pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PMinus pred1 pred2 -> failure x
  Language.Sprite.Syntax.Front.Abs.PMultiply pred1 pred2 -> failure x

transBaseType :: Language.Sprite.Syntax.Front.Abs.BaseType -> Result
transBaseType x = case x of
  Language.Sprite.Syntax.Front.Abs.BaseTypeInt -> failure x
  Language.Sprite.Syntax.Front.Abs.BaseTypeBool -> failure x
  Language.Sprite.Syntax.Front.Abs.BaseTypeVar typevarid -> failure x

transTypeVarId :: Language.Sprite.Syntax.Front.Abs.TypeVarId -> Result
transTypeVarId x = case x of
  Language.Sprite.Syntax.Front.Abs.TypeVarId varident -> failure x

transFunArgName :: Language.Sprite.Syntax.Front.Abs.FunArgName -> Result
transFunArgName x = case x of
  Language.Sprite.Syntax.Front.Abs.FunArgName varident -> failure x

transFuncAppArg :: Language.Sprite.Syntax.Front.Abs.FuncAppArg -> Result
transFuncAppArg x = case x of
  Language.Sprite.Syntax.Front.Abs.FuncAppArgBool constbool -> failure x
  Language.Sprite.Syntax.Front.Abs.FuncAppArgInt integer -> failure x
  Language.Sprite.Syntax.Front.Abs.FuncAppArgVar varident -> failure x
