-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Language.

module Language.Refinements.Predicates.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Language.Refinements.Predicates.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Language.Refinements.Predicates.Abs.Id where
  prt _ (Language.Refinements.Predicates.Abs.Id i) = doc $ showString i
instance Print Language.Refinements.Predicates.Abs.Pred where
  prt i = \case
    Language.Refinements.Predicates.Abs.HVar id_ preds -> prPrec i 0 (concatD [doc (showString "k$"), prt 0 id_, doc (showString "("), prt 0 preds, doc (showString ")")])
    Language.Refinements.Predicates.Abs.MeasureCall id_ preds -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 preds, doc (showString ")")])
    Language.Refinements.Predicates.Abs.ConstInt n -> prPrec i 0 (concatD [prt 0 n])
    Language.Refinements.Predicates.Abs.Boolean constbool -> prPrec i 0 (concatD [prt 0 constbool])
    Language.Refinements.Predicates.Abs.Var id_ -> prPrec i 0 (concatD [prt 0 id_])
    Language.Refinements.Predicates.Abs.OpExpr pred1 op pred2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 pred1, prt 0 op, prt 0 pred2, doc (showString ")")])

instance Print Language.Refinements.Predicates.Abs.ConstBool where
  prt i = \case
    Language.Refinements.Predicates.Abs.ConstTrue -> prPrec i 0 (concatD [doc (showString "true")])
    Language.Refinements.Predicates.Abs.ConstFalse -> prPrec i 0 (concatD [doc (showString "false")])

instance Print Language.Refinements.Predicates.Abs.Op where
  prt i = \case
    Language.Refinements.Predicates.Abs.EqOp -> prPrec i 0 (concatD [doc (showString "==")])
    Language.Refinements.Predicates.Abs.LessOrEqOp -> prPrec i 0 (concatD [doc (showString "<=")])
    Language.Refinements.Predicates.Abs.LessOp -> prPrec i 0 (concatD [doc (showString "<")])
    Language.Refinements.Predicates.Abs.GreaterOrEqOp -> prPrec i 0 (concatD [doc (showString ">=")])
    Language.Refinements.Predicates.Abs.GreaterOp -> prPrec i 0 (concatD [doc (showString ">")])
    Language.Refinements.Predicates.Abs.PlusOp -> prPrec i 0 (concatD [doc (showString "+")])
    Language.Refinements.Predicates.Abs.MinusOp -> prPrec i 0 (concatD [doc (showString "-")])
    Language.Refinements.Predicates.Abs.MultiplyOp -> prPrec i 0 (concatD [doc (showString "*")])
    Language.Refinements.Predicates.Abs.AndOp -> prPrec i 0 (concatD [doc (showString "&&")])
    Language.Refinements.Predicates.Abs.OrOp -> prPrec i 0 (concatD [doc (showString "||")])

instance Print [Language.Refinements.Predicates.Abs.Pred] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Language.Refinements.Predicates.Abs.Type where
  prt i = \case
    Language.Refinements.Predicates.Abs.BoolType -> prPrec i 3 (concatD [doc (showString "bool")])
    Language.Refinements.Predicates.Abs.IntType -> prPrec i 3 (concatD [doc (showString "int")])
    Language.Refinements.Predicates.Abs.VarType id_ -> prPrec i 3 (concatD [doc (showString "'"), prt 0 id_])
    Language.Refinements.Predicates.Abs.DataType id_ datatypeargs -> prPrec i 2 (concatD [prt 0 id_, doc (showString "("), prt 0 datatypeargs, doc (showString ")")])
    Language.Refinements.Predicates.Abs.FunType type_1 type_2 -> prPrec i 1 (concatD [prt 2 type_1, doc (showString "->"), prt 1 type_2])
    Language.Refinements.Predicates.Abs.ForallType id_ type_ -> prPrec i 1 (concatD [doc (showString "forall"), prt 0 id_, doc (showString "."), prt 0 type_])

instance Print Language.Refinements.Predicates.Abs.DataTypeArg where
  prt i = \case
    Language.Refinements.Predicates.Abs.DataTypeArg type_ -> prPrec i 0 (concatD [prt 0 type_])

instance Print [Language.Refinements.Predicates.Abs.DataTypeArg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Language.Refinements.Predicates.Abs.Measure where
  prt i = \case
    Language.Refinements.Predicates.Abs.Measure id_ type_ -> prPrec i 0 (concatD [doc (showString "measure"), prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print [Language.Refinements.Predicates.Abs.Measure] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "\n"), prt 0 xs]

instance Print Language.Refinements.Predicates.Abs.Qualifier where
  prt i = \case
    Language.Refinements.Predicates.Abs.Qualifier id_ qualifierargs pred -> prPrec i 0 (concatD [doc (showString "qualifier"), prt 0 id_, doc (showString "("), prt 0 qualifierargs, doc (showString ")"), doc (showString ":"), prt 0 pred])

instance Print [Language.Refinements.Predicates.Abs.Qualifier] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "\n"), prt 0 xs]

instance Print Language.Refinements.Predicates.Abs.QualifierArg where
  prt i = \case
    Language.Refinements.Predicates.Abs.QualifierArg id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print [Language.Refinements.Predicates.Abs.QualifierArg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
